version: '1'

services:
  llm:
    build: llm/
    ports: 
      - 8001:8001
    networks:
      - deploy_network
    container_name: llm_app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  retrieval:
    build: retrieval/
    ports:
      - 8002:8002
    networks:
      - deploy_network
    container_name: retrieval_app

  streamlit:
    build: app/
    depends_on:
      - llm
      - retrieval
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit_app

networks:
  deploy_network:
    driver: bridge